name: missing_person_reporter
description: AenganZ 실종자 신고 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: NotoSansKR
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Regular.ttf
  #       - asset: assets/fonts/NotoSansKR-Bold.ttf
  #         weight: 700